name: C/C++ CI

on:
  push:
    branches:
      - master
      - staging
      - develop
      - feature/**
  
  pull_request:
    branches:
      - master
      - develop
      - staging

jobs:

  # =========================
  # BUILD
  # =========================

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Build project
      run: make

  # =========================
  # TEST FUNCTIONAL
  # =========================

  test_func:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run functional tests
      run: make functional_tests

  # =========================
  # TEST UNITARY
  # =========================

  test_unit:

    needs: build

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Run unit tests
      run: make unit_tests

  # =========================
  # STAGING DEPLOY
  # =========================

  deploy-staging:

    if: github.ref == 'refs/heads/staging'
    needs:
      - test_func
      - test_unit
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Simulate staging deploy
      run: echo "Deploy realizado em staging"

  # =========================
  # PRODUCTION DEPLOY
  # =========================

  deploy-production:

    if: github.ref == 'refs/heads/master'

    needs:
      - test_func
      - test_unit

    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Simulate production deploy
      run: echo "Deploy realizado em produção"
